contrib/orafce/datefuncs.c

Modify the indentation method to eliminate compilation warnings

Modify the indentation method to eliminate compilation warnings

---

contrib/orafce/orafce--3.18.sql
contrib/orafce/sql/nlssort.sql
src/Makefile.global.in
src/bin/initdb/initdb.c
src/test/regress/expected/opr_sanity_1.out
src/test/regress/expected/sanity_check_1.out
src/test/regress/expected/sequence_1.out

Automatically load orafce at initdb

---

src/backend/commands/packagecmds.c
src/test/regress/expected/packages.out
src/test/regress/sql/packages.sql

remove open cursor when drop package body

---

src/backend/commands/functioncmds.c
src/backend/commands/packagecmds.c
src/backend/parser/parse_type.c
src/include/parser/parse_type.h
src/test/regress/expected/packages.out
src/test/regress/sql/packages.sql

Fix the issue of package function can not return the defined type

---

contrib/orafce/expected/orafce.out
contrib/orafce/sql/orafce.sql
src/backend/catalog/namespace.c

issue82,support extended data type in the packege

---

src/backend/commands/packagecmds.c
src/test/regress/expected/packages.out
src/test/regress/sql/packages.sql

Fix the drop package body not working issue

---

src/backend/catalog/namespace.c
src/backend/commands/packagecmds.c
src/backend/parser/parse_func.c
src/include/catalog/namespace.h
src/include/commands/packagecmds.h
src/include/parser/parse_node.h
src/pl/plisql/src/pl_comp.c
src/pl/plisql/src/pl_exec.c
src/pl/plisql/src/plisql.h
src/test/regress/expected/packages.out
src/test/regress/sql/packages.sql

member is a private function or procedure.

Fixed package privileges. We were missing the check to test if a package

---

src/backend/access/nbtree/nbtsort.c
src/backend/commands/indexcmds.c
src/backend/storage/file/sharedfileset.c
src/backend/utils/sort/tuplesort.c
src/include/commands/defrem.h
src/include/nodes/execnodes.h
src/include/nodes/parsenodes.h
src/include/storage/sharedfileset.h
src/include/utils/tuplesort.h
src/test/regress/expected/indexing.out
src/test/regress/sql/indexing.sql

This patch adds a feature to create global unique index
details please see this blog https://www.highgo.ca/2022/10/28/cross-partition-uniqueness-guarantee-with-global-unique-index/

support create global unique index

---

src/backend/commands/tablecmds.c
src/test/regress/expected/indexing.out
src/test/regress/sql/indexing.sql

support global unique index attach and detach

support global unique index attach detach

---

contrib/orafce/expected/orafce.out
contrib/orafce/ora_date.c
contrib/orafce/sql/orafce.sql

fix bug ：BC Dates giving wrong output

fix bug 187

---

configure
src/backend/access/transam/xlog.c
src/backend/bootstrap/bootstrap.c
src/backend/catalog/Catalog.pm
src/backend/catalog/Makefile
src/backend/catalog/genbki.pl
src/backend/catalog/ora_sys_schema.sql
src/backend/postmaster/postmaster.c
src/backend/utils/Gen_fmgrtab.pl
src/backend/utils/misc/guc_funcs.c
src/backend/utils/misc/guc_tables.c
src/bin/initdb/initdb.c
src/include/utils/guc.h
src/oracle_fe_utils/Makefile

Add initdb -m,support postgres mode or oracle mode

IvorySQL:Add initdb -m,support postgres mode or oracle mode

---

src/backend/oracle_parser/liboracle_parser.c
src/backend/oracle_parser/ora_gram.y
src/backend/oracle_parser/ora_gramparse.h
src/backend/oracle_parser/ora_keywords.c
src/backend/oracle_parser/ora_scan.l
src/backend/utils/ora_errcodes.txt
src/pl/plisql/Makefile
src/pl/plisql/meson.build
src/pl/plisql/src/Makefile
src/pl/plisql/src/generate-plerrcodes.pl
src/pl/plisql/src/meson.build
src/pl/plisql/src/pl_comp.c
src/pl/plisql/src/pl_exec.c
src/pl/plisql/src/pl_funcs.c
src/pl/plisql/src/pl_gram.y
src/pl/plisql/src/pl_handler.c
src/pl/plisql/src/pl_reserved_kwlist.h
src/pl/plisql/src/pl_scanner.c
src/pl/plisql/src/pl_unreserved_kwlist.h
src/pl/plisql/src/plisql.h
src/pl/plisql/src/po/meson.build

IvorySQL:Update copyright

---

src/bin/pg_controldata/pg_controldata.c
src/bin/pg_dump/pg_backup_db.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dumpall.c
src/bin/pg_resetwal/pg_resetwal.c
src/bin/pg_upgrade/version.c
src/bin/scripts/clusterdb.c
src/bin/scripts/createdb.c
src/bin/scripts/createuser.c
src/bin/scripts/dropdb.c
src/bin/scripts/dropuser.c
src/bin/scripts/reindexdb.c
src/bin/scripts/vacuumdb.c

IvorySQL:cmd support compatible oracle

IvorySQL:cmd support compatible oracle

---

contrib/ivorysql_ora/expected/ora_misc_functions.out
contrib/ivorysql_ora/sql/ora_misc_functions.sql
src/backend/oracle_parser/ora_gram.y

long and raw are a domain with typmod that triggers assert().

IvorySQL:Long and raw are a domain with typmod that triggers assert().

---

.github/workflows/oracle_pg_regression.yml
.github/workflows/oracle_regression.yml
.github/workflows/pg_regression.yml

Add oracle-check and oracle-pg-check in actions.

IvorySQL:update workflows

---

contrib/ivorysql_ora/expected/ora_merge.out
contrib/ivorysql_ora/sql/ora_merge.sql
contrib/ivorysql_ora/src/merge/ora_merge.c

…id during merge, resulting in an assertion error

IvorySQL:fix- The source table duplicates data, and the ctid is invalid during merge, resulting in an assertion error

---

src/fe_utils/recovery_gen.c
src/interfaces/libpq/fe-connect.c

fix bug : delete some useless parameters in PGconn

---

src/fe_utils/recovery_gen.c

fix the error of 'fix the bug of pg_basebackup'

---

contrib/adminpack/Makefile
contrib/amcheck/Makefile
contrib/amcheck/expected/ivy_check_btree.out
contrib/amcheck/sql/ivy_check_btree.sql
contrib/basic_archive/Makefile
contrib/bloom/Makefile
contrib/dict_int/Makefile
contrib/dict_xsyn/Makefile
contrib/earthdistance/Makefile
contrib/intarray/Makefile
contrib/isn/Makefile
contrib/lo/Makefile
contrib/pageinspect/Makefile
contrib/passwordcheck/Makefile
contrib/pg_buffercache/Makefile
contrib/pg_freespacemap/Makefile
contrib/pg_surgery/Makefile
contrib/pg_visibility/Makefile
contrib/pg_walinspect/Makefile
contrib/pgstattuple/Makefile
contrib/tsm_system_rows/Makefile
contrib/tsm_system_time/Makefile
contrib/unaccent/Makefile
src/Makefile.global.in
src/makefiles/pgxs.mk

Support extension  amcheck basic_archive ...

Support extension

---

contrib/pageinspect/pageinspect--1.11--1.12.sql
contrib/pageinspect/pageinspect--1.5.sql
contrib/pageinspect/pageinspect--1.8--1.9.sql
contrib/pg_stat_statements/expected/dml.out
contrib/pg_stat_statements/expected/wal.out
src/backend/access/transam/xlog.c
src/backend/commands/variable.c
src/backend/postmaster/postmaster.c
src/backend/tcop/postgres.c
src/backend/utils/misc/guc_funcs.c
src/backend/utils/misc/guc_tables.c
src/backend/utils/misc/ivorysql.conf.sample
src/backend/utils/misc/ivy_guc.c
src/bin/initdb/initdb.c
src/bin/pg_dump/pg_backup_archiver.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dumpall.c
src/bin/pg_upgrade/pg_upgrade.c
src/include/utils/guc.h
src/include/utils/guc_hooks.h
src/include/utils/ora_compatible.h
src/oracle_fe_utils/ora_string_utils.c
src/oracle_test/regress/expected/case_conversion.out
src/oracle_test/regress/expected/case_conversion_1.out
src/oracle_test/regress/expected/case_conversion_2.out
src/oracle_test/regress/expected/psql.out
src/oracle_test/regress/sql/case_conversion.sql
src/oracle_test/regress/sql/psql.sql

New framework for ivory guc variable support 

---

contrib/jsonb_plperl/Makefile
contrib/jsonb_plperl/expected/ivy_jsonb_plperl.out
contrib/jsonb_plperl/expected/ivy_jsonb_plperlu.out
contrib/jsonb_plperl/sql/ivy_jsonb_plperl.sql
contrib/jsonb_plperl/sql/ivy_jsonb_plperlu.sql

IvorySQL:compatible extension jsonb_plperl

---

contrib/jsonb_plpython/Makefile
contrib/jsonb_plpython/expected/ivy_jsonb_plpython.out
contrib/jsonb_plpython/sql/ivy_jsonb_plpython.sql

IvorySQL:compatible extension jsonb_plpython

---

contrib/hstore_plpython/Makefile
contrib/hstore_plpython/expected/ivy_hstore_plpython.out
contrib/hstore_plpython/sql/ivy_hstore_plpython.sql

IvorySQL:compatible extension hstore_plpython

---

contrib/pgcrypto/Makefile
contrib/pgcrypto/expected/3des.out
contrib/pgcrypto/expected/blowfish.out
contrib/pgcrypto/expected/blowfish_1.out
contrib/pgcrypto/expected/cast5.out
contrib/pgcrypto/expected/cast5_1.out
contrib/pgcrypto/expected/crypt-blowfish.out
contrib/pgcrypto/expected/crypt-des.out
contrib/pgcrypto/expected/crypt-md5.out
contrib/pgcrypto/expected/crypt-xdes.out
contrib/pgcrypto/expected/des.out
contrib/pgcrypto/expected/des_1.out
contrib/pgcrypto/expected/md5.out
contrib/pgcrypto/expected/pgp-armor.out
contrib/pgcrypto/expected/rijndael.out
contrib/pgcrypto/expected/sha1.out
contrib/pgcrypto/expected/sha2.out
contrib/pgcrypto/sql/3des.sql
contrib/pgcrypto/sql/blowfish.sql
contrib/pgcrypto/sql/cast5.sql
contrib/pgcrypto/sql/crypt-blowfish.sql
contrib/pgcrypto/sql/crypt-des.sql
contrib/pgcrypto/sql/crypt-md5.sql
contrib/pgcrypto/sql/crypt-xdes.sql
contrib/pgcrypto/sql/des.sql
contrib/pgcrypto/sql/md5.sql
contrib/pgcrypto/sql/pgp-armor.sql
contrib/pgcrypto/sql/rijndael.sql
contrib/pgcrypto/sql/sha1.sql
contrib/pgcrypto/sql/sha2.sql

IvorySQL:compatible extension pgcrypto

---

contrib/pg_stat_statements/Makefile
contrib/pg_stat_statements/expected/ivy_dml.out
contrib/pg_stat_statements/expected/ivy_level_tracking.out
contrib/pg_stat_statements/expected/ivy_utility.out
contrib/pg_stat_statements/sql/ivy_dml.sql
contrib/pg_stat_statements/sql/ivy_level_tracking.sql
contrib/pg_stat_statements/sql/ivy_utility.sql

IvorySQL:compatible extension pg_stat_statements

---

contrib/postgres_fdw/Makefile
contrib/postgres_fdw/expected/ivy_postgres_fdw.out
contrib/postgres_fdw/sql/ivy_postgres_fdw.sql

IvorySQL:compatible extension postgres_fdw

---

contrib/pgrowlocks/Makefile
contrib/tcn/Makefile

Makefile have ISOLATION specify test case. IvorySQL should have ORA_ISOLATION

support ORA_ISOLATION

---

contrib/xml2/Makefile
contrib/xml2/expected/ivy_xml2.out
contrib/xml2/sql/ivy_xml2.sql

IvorySQL:compatible extension xml2

---

src/oracle_test/regress/expected/xml_1.out

fix issue#527

---

GNUmakefile.in
src/Makefile.global.in
src/makefiles/pgxs.mk

IvorySQL: failed to execute make oracle-pg-check directly

---

contrib/pg_stat_statements/expected/ivy_dml.out
contrib/pg_stat_statements/expected/wal_1.out
src/oracle_test/regress/pg_regress_main.c

IvorySQL: do make oracle-installcheck successfully

---

GNUmakefile.in

IvorySQL: fix issue#544

---

contrib/ivorysql_ora/src/datatype/dsinterval.c
contrib/ivorysql_ora/src/datatype/yminterval.c
src/backend/utils/adt/Makefile
src/backend/utils/adt/varlena.c
src/include/port/win32.h
src/tools/msvc/Mkvcbuild.pm
src/tools/msvc/Project.pm
src/tools/msvc/Solution.pm
src/tools/msvc/config.bat
src/tools/msvc/setenv.bat

IvorySQL: support windows compile

---

src/backend/jit/llvm/llvmjit_expr.c

fix the malformed code in file llvmjit_expr.c

fix the malformed code in file llvmjit_expr.c 

---

src/pl/plisql/src/expected/plisql_control.out
src/pl/plisql/src/pl_gram.y
src/pl/plisql/src/sql/plisql_control.sql

Match END label with the function or procedure name.
Issue url: https://github.com/IvorySQL/IvorySQL/issues/624

Match END label with the function or procedure name

---

.github/workflows/build.yml
.github/workflows/oracle_pg_regression.yml
.github/workflows/oracle_regression.yml
.github/workflows/pg_regression.yml

Specify the version of OS in gitHub action as macos-12 to avoid action failure

Specify the version of OS in gitHub action as macos-12 to avoid action failure

---

src/backend/oracle_parser/ora_gram.y
src/oracle_test/regress/expected/alter_table.out
src/oracle_test/regress/sql/alter_table.sql

[Ivory_REL_3_Stable] fix of issue 612

[Ivory_REL_3_Stable] fix of issue 612

---

contrib/ivorysql_ora/expected/ora_xml_functions.out
contrib/ivorysql_ora/sql/ora_xml_functions.sql
contrib/ivorysql_ora/src/xml_functions/ora_xml_functions.c

Fix issue #702
https://github.com/IvorySQL/IvorySQL/issues/702

Use PG_GETARG_TEXT_P in ivy_xmlisvalid()

---

src/backend/catalog/namespace.c

recompute search path when compatible is changed.

---

configure
configure.ac

4 stable sync with pg 17.5
